#!/bin/bash

pkill -f benchmark.py

deepspeed --include "node-1:0,1,2,3" llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /xxx/xxx/LLaVA/vicuna-1.5-7b \
    --version v1 \
    --data_path /xxx/xxx/LLaVA/playground/okvqa.json \
    --image_folder /xxx/xxx/LLaVA/playground/data/textvqa/train_images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /xxx/xxx/LLaVA/projectors/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./new_checkpoints/llava-v1.5-7b-okvqa \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

deepspeed --include "node-3:0,1,2,3" llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /xxx/xxx/LLaVA/vicuna-1.5-7b \
    --version v1 \
    --data_path /xxx/xxx/LLaVA/playground/textvqa.json \
    --image_folder /xxx/xxx/LLaVA/playground/data/textvqa/train_images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /xxx/xxx/LLaVA/projectors/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./new_checkpoints/llava-v1.5-7b-textvqa \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

deepspeed --include "node-3:0,1,2,3" llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /xxx/xxx/LLaVA/vicuna-1.5-7b \
    --version v1 \
    --data_path /xxx/xxx/LLaVA/playground/gqa.json \
    --image_folder /xxx/xxx/LLaVA/playground/data/textvqa/train_images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /xxx/xxx/LLaVA/projectors/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./new_checkpoints/llava-v1.5-7b-gqa \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

deepspeed --include "node-3:0,1,2,3" llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /xxx/xxx/LLaVA/vicuna-1.5-7b \
    --version v1 \
    --data_path /xxx/xxx/LLaVA/playground/vqav2.json \
    --image_folder /xxx/xxx/LLaVA/playground/data/textvqa/train_images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /xxx/xxx/LLaVA/projectors/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./new_checkpoints/llava-v1.5-7b-vqav2 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

nohup python /amlt-code-download/benchmark.py --gpus 1 &
